---
- name: Configure Monitoring and Move Monitoring to Infra nodes
  community.kubernetes.k8s:
    api_version: v1
    state: present
    kind: ConfigMap
    name: cluster-monitoring-config
    namespace: openshift-monitoring
    merge_type:
      - strategic-merge
      - merge
    definition:
      data:
        config.yaml: |+
          enableUserWorkload: true
          alertmanagerMain:
            volumeClaimTemplate:
              spec:
                storageClassName: gp2
                volumeMode: Filesystem
                resources:
                  requests:
                    storage: 40Gi
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: "node.ocs.openshift.io/storage"
              value: "true"
              effect: NoSchedule
          prometheusK8s:
            retention: 12h
            volumeClaimTemplate:
              spec:
                storageClassName: gp2
                volumeMode: Filesystem
                resources:
                  requests:
                    storage: 200Gi
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: "node.ocs.openshift.io/storage"
              value: "true"
              effect: NoSchedule
          prometheusOperator:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: "node.ocs.openshift.io/storage"
              value: "true"
              effect: NoSchedule
          grafana:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: "node.ocs.openshift.io/storage"
              value: "true"
              effect: NoSchedule
          k8sPrometheusAdapter:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: "node.ocs.openshift.io/storage"
              value: "true"
              effect: NoSchedule
          kubeStateMetrics:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: "node.ocs.openshift.io/storage"
              value: "true"
              effect: NoSchedule
          telemeterClient:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: "node.ocs.openshift.io/storage"
              value: "true"
              effect: NoSchedule
          openshiftStateMetrics:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: "node.ocs.openshift.io/storage"
              value: "true"
              effect: NoSchedule
          thanosQuerier:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: "node.ocs.openshift.io/storage"
              value: "true"
              effect: NoSchedule
