---
- name: Set Custom Console Banner name
  community.kubernetes.k8s:
    api_version: operator.openshift.io/v1
    state: present
    merge_type:
      - strategic-merge
      - merge
    kind: Console
    name: cluster
    definition:
      spec:
        customization:
          customProductName: "{{ cluster_name }}"

- name: Set custom notification banner
  community.kubernetes.k8s:
    api_version: console.openshift.io/v1
    state: present
    merge_type:
      - strategic-merge
      - merge
    kind: ConsoleNotification
    definition:
      metadata:
        name: example
      spec:
        text: "{{ cluster_name }}"
        location: BannerTop
        color: "{{ text_colour }}"
        backgroundColor: "{{ banner_colour }}"
