---

- name: Ensure ingress controllers affinity to infra nodes and new ingress certificate is defined
  community.kubernetes.k8s:
    api_version: operator.openshift.io/v1
    state: present
    kind: IngressController
    name: default
    namespace: openshift-ingress-operator
    merge_type:
      - strategic-merge
      - merge
    definition:
      spec:
        replicas: 2
        unsupportedConfigOverrides:
          externalTrafficPolicy: Cluster
        endpointPublishingStrategy:
          loadBalancer:
            scope: Internal
            providerParameters:
              type: AWS
              aws:
                type: NLB
          type: LoadBalancerService
        nodePlacement:
          nodeSelector:
            matchLabels:
              node-role.kubernetes.io/infra: ""
          tolerations:
          - key: "node.ocs.openshift.io/storage"
            value: "true"
            effect: NoSchedule

- name: Verify the IngressController Pods is present
  community.kubernetes.k8s_info:
    kind: Pod
    namespace: openshift-ingress-operator
  register: ingress_operator
  until: "ingress_operator | json_query('resources[].status.containerStatuses[?ready==`true`][]') | length == 2"
  retries: 30
  delay: 10

